# these should all probably get resolved

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'lib/artifactory/resources/base.rb'

Lint/UselessAssignment:
  Exclude:
    - 'lib/artifactory/resources/build_component.rb'
    - 'lib/artifactory/resources/repository.rb'
    - 'lib/artifactory/resources/user.rb'
    - 'spec/integration/resources/artifact_spec.rb'
